<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="UserMacros">
    <SfmlDir>$(SolutionDir)SFML\SFML-2.5.1</SfmlDir>
    <SfmlSuffix Condition="'$(Configuration)'=='Debug'">-d</SfmlSuffix>
    <SfmlSuffix Condition="'$(Configuration)'!='Debug'"></SfmlSuffix>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <!-- Без этого исходник без BOM читается в системной кодировке,
           и кириллица в литералах приходит не та, что набрана. -->
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
      <ConformanceMode>true</ConformanceMode>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>SFML_STATIC;NOMINMAX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>$(SfmlDir)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(SfmlDir)\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>sfml-graphics-s$(SfmlSuffix).lib;sfml-window-s$(SfmlSuffix).lib;sfml-system-s$(SfmlSuffix).lib;sfml-audio-s$(SfmlSuffix).lib;sfml-network-s$(SfmlSuffix).lib;ws2_32.lib;opengl32.lib;freetype.lib;winmm.lib;gdi32.lib;openal32.lib;flac.lib;vorbisenc.lib;vorbisfile.lib;vorbis.lib;ogg.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
